killall xmrig;
killall dos64;
killall dos32;
rm -rf cd /tmp/dos64;
rm -rf cd /tmp/dos32;
rm -rf cd /root/dos64;
rm -rf cd /root/dos32;
rm -rf cd /root/c3pool;
rm -rf cd /tmp/dos24;
rm -rf cd /tmp/dos26;
reboot;